version: 0.2

phases:
  install:
    commands:
      - echo "Preparing build environment..."
  build:
    commands:
      - echo "Generating .env file..."
      - |
        cat > .env <<EOL
        APP_NAME=Laravel
        APP_ENV=local
        APP_KEY=base64:pA5KB1D+fw5wBTw8/B+rb2ZDPFGMhhFZ4DDjLDoLt2Y=
        APP_DEBUG=true
        APP_URL=http://laravel.test

        APP_LOCALE=en
        APP_FALLBACK_LOCALE=en
        APP_FAKER_LOCALE=en_US

        APP_MAINTENANCE_DRIVER=file
        PHP_CLI_SERVER_WORKERS=4
        BCRYPT_ROUNDS=12

        LOG_CHANNEL=stack
        LOG_STACK=single
        LOG_DEPRECATIONS_CHANNEL=null
        LOG_LEVEL=debug

        DB_CONNECTION=mysql
        DB_HOST=db
        DB_PORT=3306
        DB_DATABASE=laravel
        DB_USERNAME=laravel
        DB_PASSWORD=secret

        SESSION_DRIVER=redis
        SESSION_LIFETIME=120
        SESSION_ENCRYPT=false
        SESSION_PATH=/
        SESSION_DOMAIN=null

        CACHE_STORE=redis
        QUEUE_CONNECTION=redis
        BROADCAST_CONNECTION=log

        REDIS_CLIENT=phpredis
        REDIS_HOST=redis
        REDIS_PASSWORD=null
        REDIS_PORT=6379

        FILESYSTEM_DISK=local

        MAIL_MAILER=log
        MAIL_SCHEME=null
        MAIL_HOST=mailpit
        MAIL_PORT=1025
        MAIL_USERNAME=null
        MAIL_PASSWORD=null
        MAIL_FROM_ADDRESS="hello@example.com"
        MAIL_FROM_NAME="${APP_NAME}"

        AWS_ACCESS_KEY_ID=
        AWS_SECRET_ACCESS_KEY=
        AWS_DEFAULT_REGION=us-east-1
        AWS_BUCKET=
        AWS_USE_PATH_STYLE_ENDPOINT=false

        VITE_APP_NAME="${APP_NAME}"
        EOL

      # Copy Dockerfile to root
      - echo "Copying Dockerfile to root..."
      - cp docker/production/Dockerfile Dockerfile
      - cp docker/production/.dockerignore  .dockerignore

  post_build:
    commands:
      - echo ".env file generated successfully and Dockerfile copied to root."

artifacts:
  files:
    - '**/*'
