version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"
    ECR_APP_REPO: "463470945909.dkr.ecr.eu-west-2.amazonaws.com/syncastor/feed/production"
    S3_ENV_PATH: "s3://my-bucket/path/.env"  # adjust as needed

phases:
  install:
    commands:
      - echo "AWS CLI version:"
      - aws --version
      - echo "AWS region: $AWS_REGION"
      - echo "ECR repo: $ECR_APP_REPO"
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_APP_REPO

  pre_build:
    commands:
      - SHORT_COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - export BUILD_TAG=$(date +%Y-%m-%d-%H-%M-%s)-$SHORT_COMMIT
      - echo "App image tag will be: $BUILD_TAG"
      - echo "Preparing .env file..."
      - cp .env.example .env
      - echo "COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION" >> .env
      - echo "BUILD_TIME=$(date +%Y-%m-%d-%H-%M-%s)" >> .env
      - cat .env

  build:
    commands:
      - echo "Building base image..."
      - docker build -f ./cicd/production/base.Dockerfile -t $ECR_APP_REPO:base-$BUILD_TAG .
      - docker tag $ECR_APP_REPO:base-$BUILD_TAG $ECR_APP_REPO:latest-base
      - echo "Base image build complete. Now pushing base image..."
      - docker push $ECR_APP_REPO:base-$BUILD_TAG
      - docker push $ECR_APP_REPO:latest-base
      - echo "Base image pushed successfully!"
      - echo "Building vendor image..."
      - docker build -f ./cicd/production/vendor.Dockerfile -t $ECR_APP_REPO:vendor-$BUILD_TAG .
      - docker tag $ECR_APP_REPO:vendor-$BUILD_TAG $ECR_APP_REPO:latest-vendor
      - echo "Vendor image build complete. Now pushing vendor image..."
      - docker push $ECR_APP_REPO:vendor-$BUILD_TAG
      - docker push $ECR_APP_REPO:latest-vendor
      - echo "Vendor image pushed successfully!"

artifacts:
  files:
    - '**/*'
  discard-paths: no
