version: 0.2

env:
  variables:
    AWS_REGION: 'eu-west-2'
    ECR_APP_REPO: '463470945909.dkr.ecr.eu-west-2.amazonaws.com/syncastor/feed/production'
    S3_ENV_PATH: 's3://my-bucket/path/.env'

phases:
  install:
    commands:
      - 'echo "AWS CLI version:"'
      - 'aws --version'
      - 'echo "AWS region: $AWS_REGION"'
      - 'echo "ECR repo: $ECR_APP_REPO"'
      - 'aws sts get-caller-identity'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_APP_REPO'

  pre_build:
    commands:
      - 'SHORT_COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)'
      - 'export BUILD_TAG=$(date +%Y-%m-%d-%H-%M)-$SHORT_COMMIT'
      - 'echo "App image tag will be: $BUILD_TAG"'

  build:
    commands:
#      - 'echo "Building base image..."'
#      - 'Any change in base.docker'
#      - 'docker build -f ./cicd/production/base.Dockerfile -t $ECR_APP_REPO:base-$BUILD_TAG .'
#      - 'docker tag $ECR_APP_REPO:base-$BUILD_TAG $ECR_APP_REPO:latest-base'
#      - 'echo "Base image build complete. Now pushing base image..."'
#      - 'docker push $ECR_APP_REPO:base-$BUILD_TAG'
#      - 'docker push $ECR_APP_REPO:latest-base'
#      - 'echo "Base image pushed successfully!"'
#
#      - 'echo "Building vendor image..."'
#      - 'docker build -f ./cicd/production/vendor.Dockerfile -t $ECR_APP_REPO:vendor-$BUILD_TAG .'
#      - 'docker tag $ECR_APP_REPO:vendor-$BUILD_TAG $ECR_APP_REPO:latest-vendor'
#      - 'echo "Vendor image build complete. Now pushing vendor image..."'
#      - 'docker push $ECR_APP_REPO:vendor-$BUILD_TAG'
#      - 'docker push $ECR_APP_REPO:latest-vendor'
#      - 'echo "Vendor image pushed successfully!"'
      -
      - 'echo "Building nginx image..."'
      - 'TIMESTAMP=$(date +%Y%m%d%H%M%S)'
      - 'if [ -f ./cicd/production/nginx.conf ]; then cp ./cicd/production/nginx.conf nginx.conf; fi'
      - 'if [ -f nginx.conf ]; then cp nginx.conf nginx.conf.bak_$TIMESTAMP; fi'
      - 'docker build -f ./cicd/production/nginx.Dockerfile -t $ECR_APP_REPO:nginx-$BUILD_TAG .'
      - 'docker tag $ECR_APP_REPO:nginx-$BUILD_TAG $ECR_APP_REPO:latest-nginx'
      - 'echo "Nginx image build complete. Now pushing nginx image..."'
      - 'docker push $ECR_APP_REPO:nginx-$BUILD_TAG'
      - 'docker push $ECR_APP_REPO:latest-nginx'
      - 'if [ -f nginx.conf ]; then rm nginx.conf; fi'
      - 'if [ -f nginx.conf.bak_$TIMESTAMP ]; then cp nginx.conf.bak_$TIMESTAMP nginx.conf; fi'
      - 'echo "Nginx image pushed successfully!"'
      -
      - 'echo "Preparing .env file..."'
      - 'cp .env.example .env'
      - 'echo "COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION" >> .env'
      - 'echo "BUILD_TIME=$(date +%Y-%m-%d-%H-%M-%s)" >> .env'
      - 'cat .env'
      -
      - 'cp ./cicd/production/app.Dockerfile Dockerfile'

artifacts:
  files:
    - '**/*'
  discard-paths: no
