version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"
    ECR_APP_REPO: "463470945909.dkr.ecr.eu-west-2.amazonaws.com/syncastor/feed/production/app"

phases:
  install:
    commands:
      - 'echo "AWS CLI version:"'
      - 'aws --version'
      - 'echo "AWS region:" $AWS_REGION'
      - 'echo "ECR repo:" $ECR_APP_REPO'
      - 'aws sts get-caller-identity'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_APP_REPO'

  pre_build:
    commands:
      - 'export APP_TAG=$(date +%Y%m%d%H%M)'
      - 'echo "App image tag will be: $APP_TAG"'

  build:
    commands:
      - 'echo "Building application image..."'
      - 'cp ./cicd/production/base.Dockerfile ./Dockerfile'
      - 'docker build -f Dockerfile -t $ECR_APP_REPO:$APP_TAG .'
      - 'docker tag $ECR_APP_REPO:$APP_TAG $ECR_APP_REPO:latest'

  post_build:
    commands:
      - 'echo "Pushing application image..."'
      - 'docker push $ECR_APP_REPO:$APP_TAG'
      - 'docker push $ECR_APP_REPO:latest'
      - 'echo "App image pushed with tags: $APP_TAG and latest"'
